branch-defaults:
  main:
    environment: topFeed-recreate
    group_suffix: null
global:
  application_name: topFeed-backend2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application

option_settings:
  aws:elb:listener:443:
    ListenerProtocol: HTTPS
    SSLCertificateId: arn:aws:acm:us-east-2:381492038614:certificate/ea213b43-bbce-455c-92b8-47d21d1b9937
    InstancePort: 80
  aws:elb:listener:80:
    ListenerEnabled: true
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application